name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master # Recomendo trocar @master por @v3
        id: snake-gif
        with:
          github_user_name: guilhermelbr

          # --- ADICIONE AS LINHAS DE COR AQUI ---
          # Exemplo: cobra azul e pontos verdes
          color_snake: "#0070F3"
          color_dots: "#c0, #80, #60, #40, #20" 
          # ------------------------------------

          # Substitu√≠ 'svg_out_path' por 'outputs:' para gerar os 2 arquivos
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
